version: "3.1"
serrvices:
  db:
    image: mariadb
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: mariadb
      SPRING_DATASOURCE_USERMANE: root
      MARIADB_ROOT_PASSWORD: my-secret-pw
    ports: 
      - "3306:3306"
    networks:
      - rede
  app:
    image: node:lts-alpine
    ports:
      - "3000:3000"
    working_dir: "/home/node/app"
    volumes:
      - ./app:/home/node/app 
    command: "npm start"
    networks:
      - rede
  api:
    build:
      context: ./api
      target: service  
    networks:
      - rede

networks:
  rede:
    driver: "bridge"